#ifndef WRI_PROJECT_DOC_INCLUDES_H
#define WRI_PROJECT_DOC_INCLUDES_H
namespace WRI_PROJECT
{
 enum file_type  {FILE_VLOG,FILE_SVLOG, FILE_VHDL,FILE_SYSTEMC,FILE_XML,FILE_TCL};
}
#endif // WRI_PROJECT_DOC_INCLUDES_H

